# Generated by Django 4.2 on 2024-05-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg",
                max_length=500,
            ),
        ),
    ]
